version: '3.7'

services:
  annotator:
    container_name: annotator
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
    ports:
      - "80:8000"
  # nginx:
  #   container_name: nginx
  #   build: ./nginx
  #   volumes:
  #     - static:/static
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - annotator

volumes:
  static: