version: '3.7'

services:
  annotator:
    container_name: annotator
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
      - ./certs:/certs
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - annotator

volumes:
  static: