version: '3.7'

services:
  annotator:
    container_name: annotator
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"
  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
      - ./certs:/certs
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - annotator

volumes:
  static: