version: "3.9"
   
services:
  envoy:
    image: envoyproxy/envoy-alpine:v1.19-latest
    container_name: envoy
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - ./config.yaml:/etc/envoy/envoy.yaml
      - ./certs:/etc/certs
  storytelling:
    build: .
    container_name: annotator
    environment:
      - port=8000

